#!/bin/sh

BOOTER=192.168.1.89

case "$1" in
'm')
	mount ${BOOTER}:/export/backup /Users/stephenfitch/mountpoints/booter_backup
        ;;

'u')
        umount ${BOOTER}:/export/backup 
        ;;

*)
        echo "Usage: $0 { m | u }"
        exit 1
        ;;

esac
exit 0
