#!/bin/bash

sysctl -w kern.ipc.somaxconn=512
sysctl -w net.inet.tcp.mssdflt=1460
sysctl -w net.inet.tcp.sendspace=98304
sysctl -w net.inet.tcp.recvspace=98304
sysctl -w kern.ipc.maxsockbuf=1048576
sysctl -w net.inet.udp.maxdgram=57344
sysctl -w net.inet.udp.recvspace=42080
sysctl -w net.local.stream.sendspace=98304
sysctl -w net.local.stream.recvspace=98304
sysctl -w net.inet.tcp.delayed_ack=0
sysctl -w net.inet.tcp.rfc1323=1
sysctl -w net.inet.tcp.rfc1644=1
sysctl -w net.inet.tcp.newreno=1
