#!/bin/sh

MOZILLA_FIVE_HOME="/l/p/firefox/latest"
export MOZILLA_FIVE_HOME

url="$1"
if [ "x$url" = "x" ]; then
  url="about:blank"
fi

if $MOZILLA_FIVE_HOME/mozilla-xremote-client openURL\("$url"\); then
  exit 0
fi
exec $MOZILLA_FIVE_HOME/firefox "$url"

