#!/bin/sh
# Java heap size, in megabytes
JAVA_HEAP_SIZE=64
DEFAULT_JAVA_HOME="/usr/jdk/instances/jdk1.5.0/jre"
if [ "$JAVA_HOME" = "" ]; then
JAVA_HOME="$DEFAULT_JAVA_HOME"
fi
exec "$JAVA_HOME/bin/java" -mx${JAVA_HEAP_SIZE}m ${JEDIT} -classpath "/l/p/jedit/4.3pre3/jedit.jar" org.gjt.sp.jedit.jEdit $@
