#!/usr/bin/perl

$months{"Jan"} = "01";
$months{"Feb"} = "02";
$months{"Mar"} = "03";
$months{"Apr"} = "04";
$months{"May"} = "05";
$months{"Jun"} = "06";
$months{"Jul"} = "07";
$months{"Aug"} = "08";
$months{"Sep"} = "09";
$months{"Oct"} = "10";
$months{"Nov"} = "11";
$months{"Dec"} = "12";

while ($line = <>) {
	if ($line =~ /^Date:.+\s(\d+)\s(\w\w\w)\s(\d+)/) {
		$key = $3 . "-" . $months{$2} . "-" . sprintf("%2.2d", $1);
		$dates{$key}++;
	}
}

foreach $k (sort keys %dates) {
	printf "%-77s%2d\n", "$k " . "#" x $dates{$k}, $dates{$k};
}
